// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Sample API
//
//	This is a sample Golang API.
//	Schemes:
//	  http
//	Host: localhost:8080
//	BasePath: /api/v1
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
